num1 = int(input())
num2 = int(input())
num3 = int(input())
num4 = int(input())
num5 = int(input())

print("Digite um numero inteiro:")
print("Digite um numero inteiro:")
print("Digite um numero inteiro:")
print("Digite um numero inteiro:")
print("Digite um numero inteiro:")
print(f"Numero 1: {num1}")
print(f"Numero 2: {num2}")
print(f"Numero 3: {num3}")
print(f"Numero 4: {num4}")
print(f"Numero 5: {num5}")